#!/usr/bin/env python3
"""Generate polished Earth Online block and machine textures with Agnes.

Python/Pillow is only used for download, crop, downscale, and validation. The
visual source image is generated by Agnes.
"""

from __future__ import annotations

import argparse
import base64
import json
import pathlib
import re
import time
import urllib.parse

import requests
from PIL import Image


ROOT = pathlib.Path(__file__).resolve().parents[1]
ASSETS = ROOT / "neoforge-26.2" / "src" / "main" / "resources" / "assets" / "earth_online"
TMP = ROOT / "tmp" / "imagegen" / "agnes-block-textures"
PROVIDERS = pathlib.Path(r"C:\Users\du_ji\WorkBuddy\agnes\providers.json")

MODEL = "agnes-image-2.1-flash"
ENDPOINT = "https://apihub.agnes-ai.com/v1/images/generations"

BLOCKS = {
    "jaw_crusher": ("heavy jaw crusher machine block face, dark steel frame, two large toothed crushing jaws, riveted side plates, no hazard labels"),
    "ball_mill": ("industrial ball mill machine block face, rotating drum, blue gray steel, circular service hatch"),
    "sieve": ("vibrating sieve machine block face, square mesh screen, pale green frame, visible grid"),
    "magnetic_separator": ("magnetic separator machine block face, horseshoe magnet symbol, red and cyan coils, dark steel"),
    "flotation_cell": ("flotation cell machine block face, cyan tank window, bubbles, teal metal rim"),
    "ore_roaster": ("ore roaster furnace block face, orange glowing hot chamber, dark refractory brick, sulfur vent"),
    "reduction_furnace": ("reduction furnace block face, bright molten core, black steel shell, red heat glow"),
    "leaching_tank": ("leaching tank block face, green chemical vessel, pipe fittings, acid-safe industrial coating"),
    "electrolytic_cell": ("electrolytic cell block face, blue electrolyte window, copper electrodes, electric arcs"),
    "powder_press": ("powder press block face, hydraulic press plate, compacting die, tan powder tray"),
    "chemical_reactor": ("chemical reactor block face, round pressure vessel, green gauge, bolted hatch, pipes"),
    "distillation_column": ("distillation column block face, tall silver tray column, stacked plates, blue gauge"),
    "mixer": ("industrial mixer block face, mixing blades visible in round window, olive steel body"),
    "crystallizer": ("crystallizer block face, icy blue crystal chamber, white crystals, steel frame"),
    "industrial_kiln": ("industrial kiln block face, refractory brick arch, hot orange firing chamber, steel bands"),
    "gas_separator": ("gas separator block face, pressure gauges, blue gas canister window, silver valves"),
    "fertilizer_granulator": ("fertilizer granulator block face, green granule drum, hopper and pellets"),
    "polymerizer": ("polymerizer block face, purple resin vessel, polymer chain motif, bolted steel"),
    "steam_cracker": ("steam cracker block face, tall heated cracking coils, orange tubes, black steel shell"),
    "synthesis_loop": ("synthesis loop block face, high pressure loop pipes, green reactor ring, gauges"),
    "absorption_tower": ("absorption tower block face, packed tower with blue liquid spray, vertical column, vents"),
    "industrial_machine_casing": ("modular industrial machine casing, reinforced steel panels, bolts, dark gray, neutral connector block"),
    "steel_process_pipe": ("steel process pipe block, thick industrial pipe cross-section, flanges, blue gray metal"),
    "control_panel": ("industrial control panel block face, small colored indicator lights, switches, dark screen, metal frame"),
}


def load_agnes_key() -> str:
    raw = PROVIDERS.read_text(encoding="utf-8", errors="ignore")
    try:
        data = json.loads(raw)
        keys = data["agnes"]["keys"]
        if isinstance(keys, list) and keys:
            return str(keys[0])
    except Exception:
        pass

    # Fallback for historically hand-edited provider files with a damaged later entry.
    agnes_pos = raw.find('"agnes"')
    if agnes_pos < 0:
        raise RuntimeError("Agnes provider not found in providers.json.")
    next_provider = raw.find('\n  "', agnes_pos + 8)
    agnes_raw = raw[agnes_pos: next_provider if next_provider > agnes_pos else len(raw)]
    keys_match = re.search(r'"keys"\s*:\s*\[(.*?)\]', agnes_raw, re.S)
    if not keys_match:
        raise RuntimeError("Agnes key list not found in providers.json.")
    keys = re.findall(r'"([^"]+)"', keys_match.group(1))
    if not keys:
        raise RuntimeError("Agnes provider has no usable keys.")
    return keys[0]


def prompt_for(block_id: str, descriptor: str) -> str:
    return (
        "Create one polished Minecraft mod block texture for Earth Online.\n"
        f"Block id: {block_id}\n"
        f"Subject: {descriptor}.\n"
        "Style: high-quality Minecraft-inspired 64x64 pixel-art block texture, orthographic square front view, "
        "readable silhouette at small in-game scale, industrial realism, crisp pixel shapes, strong contrast, no text, "
        "no letters, no pseudo-letters, no numbers, no labels, no watermark, no UI, no inventory mockup.\n"
        "Composition: centered machine face or block surface, fills most of the square, clear iconic feature, "
        "subtle pixel noise and material detail, no perspective scene, no background outside the texture.\n"
        "Output should be a single seamless-ish square texture suitable for a Minecraft block face."
    )


def request_image(key: str, block_id: str, descriptor: str, attempts: int = 5) -> bytes:
    body = {
        "model": MODEL,
        "prompt": prompt_for(block_id, descriptor),
        "size": "1024x1024",
        "n": 1,
    }
    last_error: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            response = requests.post(
                ENDPOINT,
                headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                json=body,
                timeout=600,
            )
            response.raise_for_status()
            payload = response.json()
            break
        except requests.RequestException as exc:
            last_error = exc
            if attempt >= attempts:
                raise
            wait = min(120, 10 * attempt)
            print(f"  request failed for {block_id}, retry {attempt}/{attempts} after {wait}s: {exc}", flush=True)
            time.sleep(wait)
    else:
        raise RuntimeError(f"Agnes request failed for {block_id}: {last_error}")

    data = payload.get("data") or []
    if not data:
        raise RuntimeError(f"Agnes returned no image data for {block_id}: {payload}")
    image = data[0]
    if isinstance(image, dict) and image.get("b64_json"):
        return base64.b64decode(image["b64_json"])
    url = image.get("url") or image.get("image_url") if isinstance(image, dict) else None
    if not url:
        raise RuntimeError(f"Unsupported Agnes image payload for {block_id}: {payload}")
    if url.startswith("data:image"):
        return base64.b64decode(url.split(",", 1)[1])
    parsed = urllib.parse.urlparse(url)
    if not parsed.scheme:
        raise RuntimeError(f"Invalid image url for {block_id}: {url}")
    for attempt in range(1, attempts + 1):
        try:
            download = requests.get(url, timeout=600)
            download.raise_for_status()
            return download.content
        except requests.RequestException as exc:
            last_error = exc
            if attempt >= attempts:
                raise
            wait = min(120, 10 * attempt)
            print(f"  download failed for {block_id}, retry {attempt}/{attempts} after {wait}s: {exc}", flush=True)
            time.sleep(wait)
    raise RuntimeError(f"Agnes image download failed for {block_id}: {last_error}")


def downscale_block(source: pathlib.Path, target: pathlib.Path, size: int) -> None:
    img = Image.open(source).convert("RGBA")
    side = min(img.width, img.height)
    left = (img.width - side) // 2
    top = (img.height - side) // 2
    img = img.crop((left, top, left + side, top + side))
    # Downsample in stages to preserve recognizable shapes without mushy blur.
    for intermediate in (256, 128, 64, 32):
        if img.width > intermediate > size:
            img = img.resize((intermediate, intermediate), Image.Resampling.LANCZOS)
    img = img.resize((size, size), Image.Resampling.BICUBIC)
    target.parent.mkdir(parents=True, exist_ok=True)
    img.save(target)


def make_montage(block_ids: list[str], size: int) -> pathlib.Path:
    thumbs = []
    for block_id in block_ids:
        path = ASSETS / "textures" / "block" / f"{block_id}.png"
        if path.exists():
            thumbs.append((block_id, Image.open(path).convert("RGBA").resize((32, 32), Image.Resampling.NEAREST)))
    if not thumbs:
        raise RuntimeError("No generated textures found for montage.")
    cols = 6
    rows = (len(thumbs) + cols - 1) // cols
    montage = Image.new("RGBA", (cols * 40, rows * 40), (24, 24, 24, 255))
    for i, (_block_id, thumb) in enumerate(thumbs):
        x = (i % cols) * 40 + 4
        y = (i // cols) * 40 + 4
        montage.alpha_composite(thumb, (x, y))
    out = TMP / f"block_texture_montage_{size}px.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    montage.save(out)
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="regenerate textures even if final PNG exists")
    parser.add_argument("--only", nargs="*", default=[], help="specific block ids to generate")
    parser.add_argument("--limit", type=int, default=0, help="only generate first N selected textures")
    parser.add_argument("--size", type=int, default=64, choices=[16, 32, 64], help="final texture size")
    args = parser.parse_args()

    selected = args.only or list(BLOCKS)
    unknown = [block_id for block_id in selected if block_id not in BLOCKS]
    if unknown:
        raise SystemExit(f"Unknown block ids: {', '.join(unknown)}")

    key = load_agnes_key()
    TMP.mkdir(parents=True, exist_ok=True)
    generated = 0
    for block_id in selected:
        if args.limit and generated >= args.limit:
            break
        final = ASSETS / "textures" / "block" / f"{block_id}.png"
        raw = TMP / f"{block_id}.png"
        if final.exists() and not args.force:
            print(f"skip existing {block_id}")
            continue
        print(f"generating {block_id} with Agnes ...", flush=True)
        content = request_image(key, block_id, BLOCKS[block_id])
        raw.write_bytes(content)
        downscale_block(raw, final, args.size)
        generated += 1
        time.sleep(1.0)

    montage = make_montage(selected, args.size)
    print(f"Agnes block texture generation complete: generated={generated}, montage={montage}")


if __name__ == "__main__":
    main()
